name: chat4kids
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  provider:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  dynamic: ^0.0.5
  easy_dynamic_theme: ^2.3.1
  image_picker: ^1.0.7
  mailer: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/confetti3.jpeg
    - assets/KidsAppnoback.png
    - assets/giulia.jpeg